import { CardProps } from "../../atoms/Card";

export const POSTS: CardProps[] = [
  {
    id: "1",
    image: "https://picsum.photos/200?random=1",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Calculus II Book",
    description: "Updated edition of the calculus book, in excellent condition.",
    price: "$35,000",
    variant: "article",
    userName: "Laura Gomez",
    major: "Civil Engineering",
    postType: "product",
    contact: "320 456 7890",
  },
  {
    id: "2",
    image: "https://picsum.photos/200?random=2",
    profileImage: "https://randomuser.me/api/portraits/men/46.jpg",
    title: "Private Programming Lessons",
    description: "Offering personalized tutoring for beginners in Java and Python.",
    price: "$25,000",
    variant: "article",
    userName: "Carlos Perez",
    major: "Systems Engineering",
    postType: "service",
    contact: "310 222 3344",
  },
  {
    id: "3",
    image: "https://picsum.photos/200?random=3",
    profileImage: "https://randomuser.me/api/portraits/men/52.jpg",
    title: "Transportation to North Campus",
    description: "I travel daily from Bosa to the north campus, one seat available.",
    price: "$10,000",
    variant: "article",
    userName: "Daniel Rojas",
    major: "Law",
    postType: "service",
    contact: "300 555 2299",
  },
  {
    id: "4",
    image: "https://picsum.photos/200?random=4",
    profileImage: "https://randomuser.me/api/portraits/women/65.jpg",
    title: "Looking for AI Project Partner",
    description: "I need someone with basic knowledge of Python and machine learning.",
    variant: "article",
    userName: "Maria Torres",
    major: "Systems Engineering",
    postType: "request",
    contact: "315 777 8888",
  },
  {
    id: "5",
    image: "https://picsum.photos/200?random=5",
    profileImage: "https://randomuser.me/api/portraits/men/60.jpg",
    title: "Selling HP Laptop",
    description: "HP laptop, i5, 8GB RAM, 512GB SSD. Excellent condition.",
    price: "$1,500,000",
    variant: "article",
    userName: "Santiago Ruiz",
    major: "Architecture",
    postType: "product",
    contact: "312 999 0044",
  },
  {
    id: "6",
    image: "https://picsum.photos/200?random=6",
    profileImage: "https://randomuser.me/api/portraits/women/48.jpg",
    title: "Logo Design for Projects",
    description: "I create logos and visual identities for your business ideas.",
    price: "$40,000",
    variant: "article",
    userName: "Valentina Cardenas",
    major: "Graphic Design",
    postType: "service",
    contact: "311 101 2233",
  },
  {
    id: "7",
    image: "https://picsum.photos/200?random=7",
    profileImage: "https://randomuser.me/api/portraits/men/70.jpg",
    title: "Looking for Financial Math Lessons",
    description: "I'm looking for a tutor to help me with this subject.",
    variant: "article",
    userName: "Andres Lopez",
    major: "Business Administration",
    postType: "request",
    contact: "316 808 0909",
  },
  {
    id: "8",
    image: "https://picsum.photos/200?random=8",
    profileImage: "https://randomuser.me/api/portraits/women/50.jpg",
    title: "Used Bicycle for Sale",
    description: "GW bicycle in good condition, lightly used, ideal for city riding.",
    price: "$380,000",
    variant: "article",
    userName: "Camila Rodriguez",
    major: "Environmental Engineering",
    postType: "product",
    contact: "301 434 5566",
  },
];
